produit_index:
    path:     /b
    defaults: { _controller: "BikeBundle:Produit:index" }
    methods:  GET

produit_front:
    path:     /
    defaults: { _controller: "BikeBundle:Produit:front" }

produit_stat:
    path:     /stat
    defaults: { _controller: "BikeBundle:Produit:stat" }


produit_show:
    path:     /{id}/show
    defaults: { _controller: "BikeBundle:Produit:show" }
    methods:  GET

produit_showf:
    path:     /{id}/showf
    defaults: { _controller: "BikeBundle:Produit:showf" }
    methods:  GET

produit_new:
    path:     /new
    defaults: { _controller: "BikeBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "BikeBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "BikeBundle:Produit:delete" }
    methods:  DELETE
